#Allowed tool registry ids or tag strings starting with '#'. Use 'hand' to permit empty-hand veinmining.
tools = [
    "minecraft:diamond_pickaxe",
    "minecraft:golden_pickaxe",
    "minecraft:iron_pickaxe",
    "minecraft:netherite_pickaxe",
    "minecraft:stone_pickaxe",
    "minecraft:wooden_pickaxe"
]
